### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by Tombez** [agarian-2/MultiOgar-Agarian#1]
Node modules shouldn't be pushed to GitHub, instead make a `package.json` file by using `npm init` and then `-P` or `--save` flag when installing packages. That way, other people can download the repo without the packages, and then they only have to type `npm install` to download all the required packages.

**Comment by agarian-2** [comment]
Package.json has been created, though I'm not sure how to delete folders in GitHub...

**Comment by Tombez** [comment]
https://stackoverflow.com/questions/6313126/how-to-remove-a-directory-from-git-repository

**Comment by agarian-2** [comment]
*And exactly where would I put that?*

**Comment by Tombez** [comment]
Well if you want to use that command, you would paste that into your terminal and press enter, after you've navigated your terminal's path to the directory of your repository.

Although you can just use github's web interface to delete the folder.
https://webapps.stackexchange.com/questions/30495/how-to-delete-a-file-and-folder-from-github-com-repository-using-github-coms-we
By deleting all the files inside it.

**Comment by agarian-2** [comment]
That tells me almost nothing in terms of where to put it.

**Comment by Tombez** [comment]
If you're on windows you can press `Windows key + R`, then type in `cmd` and press `enter`.
